-- Делаем db "vk" текущей
USE vk;
-- Таблица сообщений
DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор строки',
  `from_user_id` int(10) unsigned NOT NULL COMMENT 'Ссылка на отправителя сообщения',
  `to_user_id` int(10) unsigned NOT NULL COMMENT 'Ссылка на получателя сообщения',
  `body` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Текст сообщения',
  `is_important` tinyint(1) DEFAULT NULL COMMENT 'Признак важности',
  `is_delivered` tinyint(1) DEFAULT NULL COMMENT 'Признак доставки',
  `created_at` datetime DEFAULT current_timestamp() COMMENT 'Время создания строки',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Время обновления строки',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Сообщения';

INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (1, 23, 13, 'Enim omnis quaerat alias alias rerum est vero. Maxime voluptates excepturi facere quis. Aut quisquam consectetur doloremque iusto veniam ab.', 1, 1, '1998-04-25 00:53:50', '2002-05-17 21:37:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (2, 14, 67, 'Voluptates architecto quibusdam nemo. Nemo beatae qui dolores accusamus illum architecto et. Doloremque est ut illo et consequatur eveniet odio.', 0, 1, '2000-02-27 12:49:08', '1999-09-04 20:24:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (3, 70, 63, 'Eos vero sed error eius quasi dolores illo sunt. Ducimus ad in ut voluptatem quod molestiae officiis. Laborum aliquid expedita perspiciatis ut reprehenderit. Excepturi quia tenetur qui autem quam et quibusdam.', 0, 0, '2001-04-26 06:31:20', '1986-03-21 00:54:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (4, 33, 71, 'Qui et ut delectus reprehenderit. Molestias veniam distinctio veritatis voluptatum incidunt rerum. A velit quidem expedita culpa. Consectetur nisi cumque sunt dolorum dolorum molestiae.', 1, 1, '1984-12-12 05:01:31', '1985-08-15 05:52:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (5, 58, 65, 'Sed necessitatibus natus rerum. Repellendus illo nulla ut eos. Odio consequatur voluptates porro.', 0, 0, '1976-05-25 08:55:22', '1977-11-01 10:28:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (6, 37, 52, 'Aut quae aut deleniti rem expedita cumque ipsa labore. Corporis labore ea dolore voluptas perferendis nemo tempore. Voluptatibus quia odit et cupiditate maiores.', 0, 0, '1989-11-04 08:24:23', '1977-05-09 18:31:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (7, 5, 22, 'Voluptas quo eveniet sunt at voluptatem. Praesentium recusandae et et quis illo animi eum quas. Odio iste sed voluptatem officia aperiam excepturi. Quae libero aspernatur provident tempore.', 0, 0, '1986-04-21 16:23:19', '1982-08-27 07:28:16');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (8, 56, 43, 'Et libero rem quae qui. Pariatur et voluptatum molestiae facere. Necessitatibus magnam ea natus adipisci consequatur. Inventore et enim commodi unde autem.', 0, 1, '1987-03-12 17:40:36', '1991-03-16 21:21:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (9, 44, 29, 'Accusantium soluta assumenda est explicabo repellendus. Soluta numquam sit reprehenderit accusamus. Et numquam ab recusandae.', 1, 0, '2005-08-26 02:56:22', '2016-10-31 04:31:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (10, 81, 2, 'In nam voluptas recusandae aperiam eveniet voluptas dolor reiciendis. Sit quod quia vel amet. Voluptatibus sequi sint suscipit consequatur suscipit eos perspiciatis voluptates.', 1, 0, '1979-07-30 16:18:15', '1996-01-14 05:41:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (11, 81, 89, 'Sapiente aut et dolores nobis molestiae vel voluptatibus. Et consequuntur saepe et hic impedit. Sed et quis reiciendis est ut quidem. Voluptate quas asperiores enim labore eius et.', 0, 0, '1996-05-23 10:45:07', '1982-04-15 16:12:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (12, 85, 22, 'Nihil est recusandae dolorem quis earum voluptatem. Voluptas dignissimos dolores possimus. Sunt id et ratione culpa. Aut sint suscipit magni quasi dolor vero ut.', 1, 0, '2015-01-26 06:31:02', '2001-07-17 00:22:32');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (13, 38, 87, 'Consequatur non eveniet quo error quia aut sint. Qui dolorem qui et dicta ea possimus. Dolorem quia at aspernatur natus illum quibusdam dolorum vel.', 1, 0, '2014-01-07 07:03:49', '1972-05-29 21:55:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (14, 36, 44, 'Eaque qui qui illum qui. Impedit minima harum cupiditate porro. Molestiae minima odio molestiae error aut error. Fuga corporis debitis eveniet unde.', 0, 0, '2014-07-12 03:00:45', '1978-03-21 14:45:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (15, 50, 72, 'Harum non voluptate recusandae ipsum perferendis ut velit. Modi quas ratione voluptates similique iure fugiat dolores. Et quae cupiditate quis aut mollitia consequuntur. Vel dolorem impedit possimus nihil.', 0, 1, '2011-03-19 08:16:52', '1994-10-21 15:21:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (16, 38, 72, 'Et qui quibusdam quis mollitia. Quis libero dignissimos ratione et. Vel tempora quas dignissimos sit ab voluptatem quia nihil. Libero quia qui quae vel aliquam.', 1, 1, '2015-06-03 12:41:31', '2013-07-24 03:42:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (17, 85, 51, 'Nisi ratione asperiores assumenda. Perspiciatis mollitia dicta sunt non beatae accusantium. Id doloremque non dolores ex incidunt. Sed tempore tempore et.', 0, 0, '1996-01-15 21:02:37', '1973-12-05 16:29:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (18, 39, 54, 'Nam ut fugiat consequatur nemo. Blanditiis omnis mollitia qui. Libero provident quam consequatur praesentium beatae quis molestias.', 0, 0, '2014-12-07 07:26:57', '1992-07-07 04:19:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (19, 14, 71, 'Vel tempora ipsa eius earum fuga tenetur. Aut quo molestiae odio voluptatem placeat. Et unde consectetur voluptates et necessitatibus.', 1, 1, '1996-07-30 21:39:12', '1983-08-05 20:46:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (20, 25, 71, 'Similique qui sint ut accusamus aut sit earum itaque. Commodi numquam commodi tempore id illum. Expedita distinctio architecto impedit nostrum non qui.', 1, 1, '1985-10-03 00:03:26', '2006-08-03 23:14:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (21, 35, 61, 'Et provident et in recusandae dolorem eligendi. Distinctio nobis labore enim sapiente debitis quam adipisci. Qui hic quibusdam maxime molestiae autem labore. Quia qui ut delectus qui explicabo unde.', 0, 0, '1971-04-13 21:15:35', '1993-02-19 10:30:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (22, 22, 40, 'Repellendus nesciunt est veritatis odio repellat harum sapiente. Porro eum perferendis voluptatum beatae. Iure sed consequatur alias nihil rerum quae. Est magni neque recusandae saepe.', 1, 1, '1994-12-18 00:18:38', '1997-01-25 09:36:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (23, 83, 78, 'Nemo accusantium veritatis qui voluptatem esse eius molestiae. Asperiores rem illum voluptatem rerum commodi.', 0, 0, '1982-07-19 18:02:35', '1988-02-13 11:57:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (24, 82, 26, 'A voluptate ipsam corrupti voluptatem et. Impedit dolores nihil doloribus dolores excepturi assumenda dolorum. Sit qui praesentium eaque natus atque et vitae voluptas. Et exercitationem maxime cumque rerum animi veniam rerum dolorem.', 0, 0, '1984-03-27 00:42:15', '1991-04-08 10:53:16');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (25, 6, 63, 'Blanditiis sapiente tempora voluptate aut esse. Deleniti at excepturi doloremque iure quia amet accusantium. Perferendis assumenda a eum voluptas tenetur occaecati.', 1, 1, '1985-03-17 02:40:29', '1979-09-13 16:33:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (26, 28, 87, 'Et fugiat in vel non. Eos dignissimos fugiat possimus sint commodi ipsum nostrum. Repellendus aut quas aspernatur praesentium facere sunt. Fuga dolor optio molestiae doloribus excepturi quae assumenda.', 1, 1, '1999-09-24 01:19:14', '2014-01-23 11:07:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (27, 51, 12, 'Amet repudiandae alias modi natus sed. Dolorem recusandae sit repellat eum voluptatem. Ipsum est nesciunt est et laudantium. Sit ex excepturi iusto eaque. Et consequatur delectus voluptatem qui molestiae quasi.', 1, 1, '1980-12-10 05:31:33', '1987-12-02 17:49:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (28, 9, 89, 'Numquam delectus et itaque voluptas quia dolor. Voluptatem ad ut id. Facere dolorem architecto amet debitis.', 1, 0, '1995-09-11 19:14:15', '2019-07-07 08:14:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (29, 98, 44, 'Assumenda totam natus sed eveniet. Ducimus est error dicta et. Sint perspiciatis mollitia voluptatem velit.', 0, 0, '2003-11-14 10:32:11', '2016-04-05 18:01:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (30, 32, 48, 'Quo dicta vel molestiae optio veritatis facere doloremque. Qui eum aut est reprehenderit voluptates incidunt. Quis suscipit vitae non laborum. Est alias nihil modi error enim.', 0, 0, '2005-09-17 14:19:15', '2015-11-11 10:07:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (31, 16, 70, 'Excepturi omnis ut rerum. Voluptatem pariatur aliquid doloremque repellendus repellendus minima et. Magnam sunt sit libero dolorem nihil provident est.', 1, 1, '1995-06-16 22:21:03', '2015-07-10 09:03:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (32, 20, 100, 'Deleniti quo aperiam accusantium pariatur aliquid mollitia. Et consectetur porro magnam neque ducimus. Quis non voluptatibus similique sit sit ut fugit.', 0, 0, '1971-10-27 09:58:58', '1980-12-06 06:05:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (33, 20, 58, 'Aspernatur animi quia consequuntur nobis natus. Deleniti asperiores error aliquid qui asperiores. Autem voluptas delectus et omnis. Quas possimus dignissimos tempore nam in et incidunt.', 0, 0, '2015-06-26 08:04:01', '1988-08-21 02:12:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (34, 54, 34, 'Sequi sed numquam et similique et mollitia. Deserunt hic molestiae officia voluptatem soluta et. Est hic vel voluptatem laboriosam. Alias sapiente soluta sed sunt cum.', 1, 1, '1997-10-31 19:20:13', '1995-03-29 07:26:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (35, 29, 78, 'Non quia laudantium sapiente cumque et delectus vel. Omnis doloribus cum eos omnis esse ea. Ipsa laboriosam aut omnis ab corporis. Soluta qui odio aperiam est.', 0, 1, '2020-01-28 07:35:27', '2014-07-06 09:44:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (36, 5, 64, 'Qui voluptas accusamus ipsa consequuntur. Alias velit dolores voluptatem eligendi natus veniam quibusdam. Autem iure sed et. Nisi ut cupiditate eius facere qui et asperiores.', 0, 0, '2007-08-10 20:34:57', '2003-07-28 14:04:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (37, 39, 27, 'Est inventore occaecati fuga tempora. Qui sint nulla temporibus ex. Voluptatem velit asperiores hic quas.', 1, 1, '1999-02-13 20:33:53', '2009-03-29 20:25:19');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (38, 3, 21, 'Occaecati ducimus similique voluptatem odit blanditiis non. Iste at tempora et eos nemo. Dolorum minus aut dolorem velit.', 1, 0, '1988-09-19 02:04:58', '1977-01-02 19:06:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (39, 4, 85, 'Fugit inventore ut animi cum sed. Ipsa in numquam assumenda modi repellat iste provident. A aut et illo non quia. In dolor sit tempora nulla quasi alias.', 0, 0, '1982-06-15 15:51:21', '1997-07-03 00:47:42');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (40, 47, 10, 'Ex dolorem eos maiores aperiam quos at aperiam velit. Molestiae ut saepe non et eum corporis fugit. Omnis corporis qui laborum explicabo.', 1, 1, '1997-04-29 07:45:03', '1989-07-08 15:53:32');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (41, 47, 74, 'Vitae quia iste voluptatem unde. Aperiam ipsum ad quae et dolores omnis. Repellendus est doloribus et praesentium corporis commodi qui. Pariatur consequatur adipisci error quibusdam animi est velit rerum.', 0, 1, '1976-11-06 20:27:24', '2013-01-23 16:27:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (42, 97, 98, 'Aperiam consequuntur est quaerat provident odit accusamus. Ut illum consequuntur fugiat ipsam placeat enim. Cupiditate aliquid illo id labore. Temporibus repellat nesciunt ea adipisci vero. Dolor vero quos sed consequatur quia reprehenderit molestias.', 0, 1, '2007-06-10 16:05:30', '2011-02-11 15:40:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (43, 86, 5, 'Eum odio quo in dolores ipsam. Excepturi sint eum dolores autem sed. Perferendis qui non eaque culpa incidunt sed ut.', 1, 0, '1996-01-04 12:53:59', '2015-06-11 23:09:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (44, 87, 83, 'Dolorem doloribus illo vero. Libero ex nam blanditiis est. Omnis voluptatum error sunt provident.', 1, 0, '1993-01-07 15:33:47', '1993-12-08 12:16:33');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (45, 48, 18, 'Voluptatem neque ut reprehenderit et necessitatibus error. Et cumque sapiente fugit animi quo ut odit. Voluptas et quidem aspernatur saepe ipsa sed.', 0, 0, '1977-07-14 17:44:32', '1998-04-21 03:39:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (46, 31, 64, 'Ut adipisci reprehenderit molestias aut. Ea aut excepturi quae voluptatum maxime eveniet. Consequuntur accusamus quisquam rerum in. Magni voluptatem est harum a corporis.', 1, 0, '2009-02-19 10:57:34', '1997-01-17 16:26:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (47, 88, 51, 'Vero est rerum iure porro dolor sequi quae. Molestias aut qui voluptatem quo eos quia et. Modi quidem eum cumque praesentium. Quidem incidunt saepe eligendi nihil. Laboriosam mollitia sed eius omnis et numquam.', 1, 1, '1976-05-12 23:14:23', '1977-04-17 17:59:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (48, 63, 7, 'Doloribus consequatur dignissimos iste ratione nesciunt itaque assumenda sapiente. Fugit rerum totam et itaque iusto. Nulla neque dolorem voluptates rem. Omnis voluptas eligendi suscipit officia quam.', 1, 1, '2009-10-14 00:20:48', '1985-05-20 00:16:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (49, 9, 17, 'Autem earum qui enim. Repellendus sed omnis distinctio voluptatum. Vel velit dolores est odio.', 1, 1, '1997-04-24 20:05:50', '2005-05-29 21:11:02');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (50, 40, 37, 'Ex sapiente quidem impedit voluptas pariatur. In ipsum rerum quia facilis corrupti.', 0, 1, '2004-09-17 22:54:52', '1981-07-02 13:15:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (51, 95, 45, 'Illum necessitatibus consequuntur vel id molestiae veritatis. Iure laudantium quisquam et. Numquam et beatae aspernatur pariatur distinctio doloremque ex ut.', 1, 1, '2019-06-05 07:11:59', '2020-07-21 08:23:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (52, 1, 33, 'Atque consequatur quasi tenetur velit sit. Autem ab natus reiciendis sunt voluptates explicabo pariatur illo. Ut et ea dolorem ut optio.', 0, 1, '2010-08-06 00:22:25', '1984-01-25 21:22:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (53, 71, 4, 'Est autem occaecati ea velit sed. Ut non totam soluta ratione mollitia at voluptatem voluptatibus. Dolor iste sit sit occaecati ipsa. Et modi corporis iure voluptate.', 0, 0, '1980-04-19 06:29:22', '2016-11-06 11:44:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (54, 53, 74, 'Quaerat iure et minima repellat deleniti perferendis voluptas iusto. Temporibus numquam dolor et magnam distinctio provident est. Asperiores voluptatem voluptatem voluptatem necessitatibus odio dolorum.', 0, 1, '2009-09-30 12:59:16', '2019-11-15 09:26:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (55, 88, 99, 'Laudantium et doloremque adipisci ut quos quaerat consequatur veniam. Perspiciatis sequi et exercitationem et. Voluptas enim quasi asperiores hic quo consectetur. Alias iure laborum et enim modi minima.', 0, 0, '2001-07-06 17:33:56', '1986-05-20 21:23:58');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (56, 84, 35, 'Eveniet provident earum et dignissimos nihil laborum. Dignissimos fuga dolor ullam veritatis. Occaecati architecto repellat in et consequatur.', 0, 0, '1995-08-12 01:23:10', '2005-12-10 01:17:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (57, 73, 80, 'Quidem itaque alias exercitationem ea eum vel delectus et. Quam delectus excepturi ratione voluptas officiis doloribus molestiae. Illo saepe necessitatibus sunt voluptatem excepturi eaque dolor. Aliquam incidunt minima ipsam vitae sit voluptatem.', 1, 0, '1988-12-30 11:16:13', '1976-08-19 12:13:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (58, 33, 58, 'Nostrum deserunt dolores accusamus repellat sed. Optio cum quasi aliquam praesentium aliquam fugit accusamus. Minima blanditiis et quia ipsam eveniet.', 1, 1, '1974-07-30 05:23:27', '2015-08-28 16:16:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (59, 85, 19, 'Voluptatem natus asperiores nemo non consequuntur saepe. Quis cumque laborum aut nesciunt. Iste illo voluptatem unde et qui inventore aut. Consequatur et voluptas earum ut mollitia sed.', 1, 0, '2001-04-19 18:33:56', '1992-02-18 01:52:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (60, 41, 33, 'Quod et ut odit quis et. Aut voluptas officia voluptas dolorem accusamus recusandae. Blanditiis reiciendis ut consequuntur molestias nesciunt beatae. Quaerat voluptate eos deserunt.', 0, 1, '2003-11-21 21:36:49', '2008-09-12 13:49:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (61, 37, 71, 'Veniam commodi autem totam. Velit voluptatem harum et. Voluptas inventore laboriosam sunt et dignissimos sed. Voluptatum temporibus non et et labore doloribus.', 0, 1, '1978-05-15 23:26:54', '2014-04-12 05:36:24');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (62, 96, 24, 'Quod inventore voluptas nostrum quisquam quae sit. Magni neque eum dolores repellat earum dolorum sed. Non corporis maxime ea a et. Nemo accusamus numquam numquam molestiae.', 1, 0, '2010-01-19 22:12:50', '1975-07-23 16:21:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (63, 22, 59, 'Voluptatem dolorem enim assumenda. Quis quia maxime nobis quasi autem.', 1, 0, '2012-05-01 08:34:59', '2016-05-16 00:53:00');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (64, 31, 30, 'Exercitationem voluptas facilis quibusdam commodi impedit. Rem sed voluptas optio.', 1, 0, '1991-03-01 13:21:33', '2010-12-11 03:11:42');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (65, 76, 71, 'Porro est natus dolores qui praesentium atque. Corrupti ex dignissimos quia voluptates quia. Nam consequatur voluptatem laboriosam maiores eum.', 0, 1, '1990-02-04 16:56:57', '2000-11-11 05:52:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (66, 67, 70, 'Debitis qui et veritatis earum ipsam ipsum sit labore. Aut eligendi at voluptatem consequatur distinctio. Dignissimos est tempora at sunt eaque aut. Placeat ut magnam assumenda inventore omnis aliquam.', 0, 0, '1997-06-01 20:45:08', '2000-07-27 13:48:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (67, 15, 67, 'Qui iste dolorum voluptates quo aut placeat. Ut beatae iure quo accusamus quasi optio. Ut quod aspernatur illum aut aperiam et et. Omnis facilis sit debitis culpa.', 0, 0, '1997-12-24 08:45:44', '2018-10-20 07:39:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (68, 3, 85, 'Est voluptates sunt quae fugiat. Fugit voluptate doloremque neque aut accusantium corrupti eos. Corrupti veritatis aut sequi minima.', 1, 0, '1979-02-16 14:27:15', '2016-01-13 22:20:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (69, 70, 56, 'Quaerat repellendus illum id illum atque doloribus aperiam reiciendis. Laudantium ut recusandae facere officia. Commodi ab cumque et laboriosam quod voluptate. Voluptatem sed commodi quas.', 1, 1, '2018-11-05 12:15:47', '1997-07-25 08:48:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (70, 59, 58, 'Quo ut in veritatis consequatur voluptatum et et asperiores. Qui veniam reprehenderit sapiente voluptas suscipit. Illo aperiam eos minima. Ad nihil optio dolore voluptas voluptatem voluptatum distinctio ut. Velit est sit consequatur inventore similique.', 0, 1, '1993-12-07 14:10:08', '2009-12-28 05:36:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (71, 54, 43, 'Aliquid nam quaerat culpa eveniet. Dolorem blanditiis officiis reprehenderit deserunt doloribus quam voluptas. Voluptatem porro expedita nihil aut velit. Debitis voluptate beatae enim vitae.', 0, 1, '1996-07-02 06:28:36', '1980-07-14 07:08:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (72, 92, 27, 'Aut totam minus asperiores officiis quasi itaque. Repellat odio provident deleniti iure. Velit perferendis iste voluptas ex. Dolores autem est magni facilis veritatis. Mollitia doloremque ut cumque nam harum.', 1, 0, '1987-06-14 15:23:46', '1978-03-23 08:07:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (73, 23, 25, 'Minus sequi tempore et doloremque amet eum. Dolorem autem mollitia rerum architecto illo. Ut perspiciatis molestiae reprehenderit.', 0, 1, '2016-05-24 15:36:14', '2004-08-30 01:15:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (74, 84, 7, 'Vero dolor aut nulla eum aut asperiores magni qui. Veniam quos debitis inventore facilis non.', 0, 1, '1983-08-18 21:09:44', '1991-12-13 02:09:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (75, 44, 24, 'Praesentium animi quia dolor qui voluptatem corporis ipsum. Debitis voluptas similique libero expedita voluptas et. Quae alias sit eos quo delectus vel sit.', 0, 0, '2012-10-19 22:53:02', '1979-01-04 09:51:02');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (76, 40, 81, 'Laudantium molestiae asperiores et consequuntur beatae ea. Harum est aspernatur odit. Quaerat architecto soluta quasi totam facilis in magnam. Sint consequatur voluptatum quae eaque dolorum.', 1, 0, '1985-06-06 12:12:45', '1984-05-03 01:03:02');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (77, 95, 36, 'Asperiores at eveniet excepturi facilis itaque. Cumque reprehenderit eligendi enim vitae. Eos consequuntur qui aliquid hic. Expedita et nisi labore voluptates magnam voluptatem.', 0, 1, '2001-08-09 23:01:27', '2019-03-19 09:39:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (78, 4, 17, 'Ipsum occaecati velit placeat. Dolor quo dolores architecto nostrum veniam quia. Laboriosam iusto voluptatem alias qui et.', 1, 1, '2018-12-13 10:45:08', '1995-11-25 13:43:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (79, 94, 35, 'Sed eaque est rerum tempora ad magni. Veritatis debitis non ea quia. Est qui sequi expedita sed sed in.', 0, 1, '1982-07-29 21:07:54', '1981-06-02 05:28:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (80, 46, 70, 'Ullam suscipit consequatur magnam consequatur magnam quia inventore. Et inventore et esse placeat. Et et perferendis ipsum nesciunt quos reprehenderit commodi eligendi.', 0, 0, '2006-09-26 19:55:31', '1973-07-28 08:21:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (81, 5, 12, 'Excepturi commodi assumenda ex ut natus qui. Cum quis mollitia facilis quidem molestiae enim fugiat. Omnis eaque laboriosam qui non ut. Unde sint minima rerum velit sit esse sapiente.', 1, 1, '2019-04-07 23:00:28', '1976-09-11 21:21:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (82, 39, 20, 'Ut est officia laborum impedit necessitatibus ab dignissimos. Nesciunt omnis quidem nesciunt asperiores eligendi voluptatibus et qui.', 1, 0, '1987-09-22 03:33:32', '1982-11-04 19:14:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (83, 78, 42, 'Vero et voluptas molestias harum quidem. Ut illum maiores quos nulla architecto sunt temporibus. Et maxime voluptatibus nisi doloremque. Eum ea aut similique aut vel provident.', 0, 0, '1970-03-12 20:05:25', '2015-11-25 23:25:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (84, 5, 48, 'Enim est sequi sed hic voluptas molestiae dolor. Nemo at natus et quia facilis illo cum. Tempora consequatur et deserunt aliquid id.', 1, 0, '2008-09-04 09:49:31', '1985-09-25 00:55:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (85, 97, 64, 'Beatae ipsum aspernatur totam explicabo. Fuga repellendus inventore ullam in accusantium. Et ipsum amet ipsam. Non aut maxime qui voluptates ex provident.', 0, 1, '2012-09-06 22:05:35', '1989-10-10 14:31:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (86, 5, 51, 'Sed qui veritatis quis eaque. Sed impedit omnis vel voluptatem.', 1, 0, '2015-02-16 19:44:25', '1987-06-16 04:18:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (87, 6, 97, 'Amet aperiam et tempora unde eum veniam. Mollitia omnis quibusdam quia harum rerum. Alias optio officia magni magnam molestiae. Veritatis odit est doloremque perspiciatis qui corrupti.', 1, 1, '1995-03-23 20:41:48', '2010-05-25 18:31:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (88, 77, 29, 'Delectus laborum velit cumque ipsum excepturi. Nobis id quia et dolorem.', 1, 1, '2006-04-07 06:05:48', '1989-01-31 01:06:42');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (89, 21, 61, 'Rerum ut debitis explicabo impedit. Occaecati eveniet eos sequi dignissimos repellat qui quo. Quisquam illum perspiciatis perferendis nam quisquam numquam. Tempore officiis voluptates ullam totam iure.', 0, 1, '2003-03-10 04:46:35', '2002-12-26 06:56:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (90, 35, 65, 'Consequatur harum delectus dolores voluptas enim. Illo cumque occaecati adipisci doloribus velit. Reiciendis sed eum minima. Alias voluptatem enim perspiciatis inventore autem explicabo.', 0, 1, '2009-08-26 20:02:18', '2017-02-06 08:59:22');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (91, 85, 75, 'Culpa perspiciatis commodi impedit qui nemo voluptatem. Est et et nesciunt sequi. Necessitatibus repellat quas est ut quo commodi optio. Iusto molestiae eum officia in similique temporibus iste dolor. Facilis corporis voluptatem reprehenderit laboriosam enim iusto.', 0, 1, '2003-01-21 10:48:21', '1971-06-08 21:58:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (92, 45, 80, 'Quia neque alias necessitatibus dolores assumenda. Similique iure quia qui aut vitae provident animi quis. Eveniet rerum nulla cum eaque. Reiciendis est ratione veniam explicabo quaerat eaque tenetur minus.', 0, 0, '1988-09-06 02:41:37', '1989-04-12 22:17:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (93, 10, 49, 'Asperiores laudantium et impedit error occaecati repellendus quod. Voluptatem beatae quos accusamus. Dolores consequatur ab qui aut.', 1, 0, '2011-10-22 22:08:49', '1970-12-16 00:35:50');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (94, 96, 4, 'Alias et asperiores tempore laborum. Ut provident consequatur fugiat autem est. Iusto nisi quia non aut.', 0, 1, '2006-10-23 07:55:47', '1988-01-17 20:10:22');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (95, 83, 41, 'Dolore in et non aut sed. Quidem tenetur non autem neque non. Nostrum et saepe consequatur et labore sint quis. Sit natus provident dolorem consequuntur officiis sint. Repudiandae velit consequatur aut a magnam perspiciatis.', 0, 1, '1995-11-01 07:45:01', '2015-08-25 17:59:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (96, 73, 88, 'Id dolores temporibus quae illo est inventore aut. Et enim et quo vel aut. Tempora vero animi voluptas doloribus.', 0, 1, '1981-07-07 08:02:28', '2015-02-19 03:24:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (97, 52, 12, 'Incidunt dicta aperiam aut ut voluptas. Autem in praesentium earum dolores et aut. Fugiat illo velit voluptate corrupti.', 1, 0, '2007-04-09 12:26:21', '1980-10-04 01:59:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (98, 8, 30, 'Nobis quia omnis saepe quod. Accusamus blanditiis officia necessitatibus reiciendis consequatur impedit blanditiis. Omnis quo voluptates earum voluptatibus molestias eos et. Aperiam ipsa consequuntur eius in et aut eaque provident.', 1, 1, '2008-10-21 08:48:57', '2007-08-05 12:01:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (99, 53, 12, 'Natus soluta non ea culpa iste sunt. Beatae consequuntur asperiores nesciunt sint in reprehenderit. Tempore est alias cumque quaerat a temporibus.', 0, 0, '1997-11-10 11:48:20', '2015-04-24 16:14:24');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`, `updated_at`) VALUES (100, 77, 50, 'Consequuntur id rerum voluptatibus eos voluptas et quis. Impedit quaerat sint praesentium omnis similique deserunt. Reiciendis dolor temporibus dolorum animi. Voluptas harum quasi cupiditate excepturi est corrupti.', 0, 1, '1987-07-16 00:36:35', '1996-05-09 07:47:38');
